version: '3'
services:
  publisher:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    environment:
      DB_HOST: "mongodb://poll:poll@mongo:27017/poll?authSource=poll"
      APP_ROLE: "PUBLISHER"
    restart: on-failure
    depends_on:
      - rabbitmq
    command: bash -c "chmod +x ./wait-for-it.sh && ./wait-for-it.sh rabbitmq:5672 -- nodemon app.js"

  mongo: 
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - "mongodb:/data/db"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  rabbitmq:
    image: "rabbitmq:3.11-management"
    ports:
      - "15672:15672"
      - "5672:5672"

volumes:
  mongodb:
    driver: local
